<?php
/**
 * Simple PDF Generator Class
 * 
 * A lightweight class for generating PDF reports using HTML and browser print functionality
 * Specifically designed for the TaskMaster admin reports
 */
class PDFGenerator {
    private $title;
    private $data = [];
    private $headers = [];
    private $filename;
    
    /**
     * Constructor
     * 
     * @param string $title The title of the PDF document
     * @param string $filename The filename for the PDF download
     */
    public function __construct($title, $filename) {
        $this->title = $title;
        $this->filename = $filename;
    }
    
    /**
     * Set the table headers
     * 
     * @param array $headers Array of header labels
     */
    public function setHeaders($headers) {
        $this->headers = $headers;
    }
    
    /**
     * Add data to the table
     * 
     * @param array $data Array of data rows
     */
    public function setData($data) {
        $this->data = $data;
    }
    
    /**
     * Generate and output the PDF
     */
    public function output() {
        // Clear any previous output
        ob_clean();
        
        // Output the HTML content
        echo $this->generateHTML();
        exit;
    }
    
    /**
     * Generate the HTML content
     * 
     * @return string The HTML content
     */
    private function generateHTML() {
        $html = '<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>' . htmlspecialchars($this->title) . '</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 20px;
            color: #333;
        }
        h1 {
            color: #0d9488;
            text-align: center;
            margin-bottom: 20px;
            font-size: 24px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
            page-break-inside: auto;
        }
        tr {
            page-break-inside: avoid;
            page-break-after: auto;
        }
        th {
            background-color: #0d9488;
            color: white;
            padding: 10px;
            text-align: left;
            font-size: 12px;
        }
        td {
            padding: 8px;
            border-bottom: 1px solid #ddd;
            font-size: 11px;
        }
        tr:nth-child(even) {
            background-color: #f2f2f2;
        }
        .footer {
            text-align: center;
            font-size: 10px;
            color: #666;
            margin-top: 30px;
            position: fixed;
            bottom: 10px;
            left: 0;
            right: 0;
        }
        @media print {
            body {
                margin: 0;
                padding: 15px;
            }
            h1 {
                font-size: 18px;
                margin-bottom: 15px;
            }
            table {
                font-size: 10px;
            }
            th, td {
                padding: 5px;
            }
            .no-print {
                display: none;
            }
            @page {
                size: A4;
                margin: 1cm;
            }
        }
        .print-button {
            background-color: #0d9488;
            color: white;
            border: none;
            padding: 10px 20px;
            border-radius: 5px;
            cursor: pointer;
            margin-bottom: 20px;
            font-weight: bold;
        }
        .print-button:hover {
            background-color: #0b7a71;
        }
    </style>
</head>
<body>
    <div class="no-print" style="text-align: center; margin-bottom: 20px;">
        <button class="print-button" onclick="window.print()">Print / Save as PDF</button>
    </div>
    
    <h1>' . htmlspecialchars($this->title) . '</h1>
    
    <table>
        <thead>
            <tr>';
        
        // Add table headers
        foreach ($this->headers as $header) {
            $html .= '<th>' . htmlspecialchars($header) . '</th>';
        }
        
        $html .= '</tr>
        </thead>
        <tbody>';
        
        // Add table rows
        foreach ($this->data as $row) {
            $html .= '<tr>';
            foreach ($row as $cell) {
                $html .= '<td>' . htmlspecialchars($cell) . '</td>';
            }
            $html .= '</tr>';
        }
        
        $html .= '</tbody>
    </table>
    
    <div class="footer">
        Generated by TaskMaster on ' . date('Y-m-d H:i:s') . '
    </div>
    
    <script>
        // Auto-print when the page loads
        window.onload = function() {
            // Small delay to ensure the page is fully loaded
            setTimeout(function() {
                window.print();
            }, 1000);
        };
    </script>
</body>
</html>';
        
        return $html;
    }
}